<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaContactoRepository extends EntityRepository
{
	public function getOne()
	{
		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['c'])
			->from('DestinyAppBundle:EmpresaContacto','c')
			  ->where($query->expr()->eq('c.estado',':estado'))
				->setParameters([':estado'=> true])
				->getQuery()->getOneOrNullResult();
	}
}
