<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaWebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaWebRepository extends EntityRepository
{
	public function getEmpresaActiva()
	{
		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['e'])
			->from('DestinyAppBundle:EmpresaWeb', 'e')
			->where($query->expr()->isNotNull('e.nombre'))
			->getQuery()->getOneOrNullResult();
	}

	public function getOne()
	{
		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['c'])
			->from('DestinyAppBundle:EmpresaWeb','c')
			->getQuery()->getOneOrNullResult();
	}
}
