<?php

namespace Destiny\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
	public function getOne($username)
	{
		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder();

		return $query->select(['u'])
			->from('DestinyAppBundle:Usuarios', 'u')
			->where($query->expr()->eq('u.usernameCanonical',':username'))
			->setParameters(['username' => $username])
			->getQuery()->getOneOrNullResult();
	}
}
