services:
    destiny_appbundle.form.type.idiomas:
        class: Destiny\AppBundle\Form\IdiomasType
        arguments: ["@doctrine.orm.entity_manager", "@translator"]
        tags:
            - { name: form.type }

    idiomas: "@destiny_appbundle.form.type.idiomas"